# This docker-compose create a Blacklist server and Mailbox server.
services:
  blacklist_server:
    build:
      context: ./blacklist
      dockerfile: Dockerfile
    image: blacklist_server_image
    container_name: blacklist_server
    network_mode: host
    stdin_open: true
    tty: true

  mailbox_server:
    build:
      context: ./mailbox
      dockerfile: Dockerfile
    image: mailbox_server_image
    container_name: mailbox_server
    network_mode: host
    stdin_open: true
    tty: true

  mailbox_client:
    build:
      context: ./mailbox
      dockerfile: Dockerfile2
    image: mailbox_client_image
    container_name: mailbox_client
    network_mode: host
    stdin_open: true
    tty: true

# NOT IN USE ANYMORE - USING HOST
#networks: 
#  my_net:
#    name: my_net
#    driver: bridge
